pedido/urls.py
from django.urls import path
from .views import criar_pedido, detalhe_pedido

app_name = 'pedido'

urlpatterns = [
    path('criar/', criar_pedido, name='criar'),
    path('detalhe/<int:pk>/', detalhe_pedido, name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views
from perfil.views import meus_pedidos, cancelar_pedido

app_name = 'perfil'

urlpatterns = [
    path('meus-pedidos/', meus_pedidos, name='meus_pedidos'),
    path('meus-pedidos/cancelar/<int:pedido_id>/', cancelar_pedido, name='cancelar_pedido'),
    path('user/register/', views.createUser, name='register'),
    path('user/logout/', views.logoutView, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from perfil.views import MyLoginView, createUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),

    path('accounts/login/', MyLoginView.as_view(), name='account_login'),
    path('accounts/signup/', createUser, name='account_signup'),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfil/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.usuario.first_name} {self.usuario.last_name}' 
    
    def clean(self):
        pass

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'

perfil/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(required=True, min_length=3,)
    last_name = forms.CharField(required=True, min_length=3,)

    class Meta:
        model = User
        fields = (
            'email','username', 'password1', 'password2',
        )

        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Digite seu nome de usuário'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Digite seu email'
            })
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('first_name', None)
        self.fields.pop('last_name', None)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_instance = self.instance

        if user_instance and user_instance.email == email:
            return email

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Este email já está em uso', code='invalid')
            )
        return email

perfil/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages, auth
from allauth.account.views import LoginView
from .forms import RegisterForm
from django.urls import reverse
from produto.models import Categoria
from pedido.models import Pedido


class MyLoginView(LoginView):
    def form_invalid(self, form):
        messages.error(self.request, "Usuário ou senha inválidos!")

        url_com_param = reverse('produto:index') + '?login_error=true'
        return redirect(url_com_param)

def createUser(request):
    loginForm = AuthenticationForm(prefix='register')
    jogos = Categoria.objects.all()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Registrado com sucesso!')
            return redirect('produto:index')
    else:
        form = RegisterForm()


    return render(
        request,
        'perfil/create-user.html',
        {
            'form': form,
            'loginForm': loginForm,
            'jogos': jogos,
        }
    )

def logoutView(request):
    auth.logout(request)
    return redirect('produto:index')


@login_required(login_url='/')
def meus_pedidos(request):
    pedidos = Pedido.objects.filter(usuario=request.user).select_related('usuario').prefetch_related('itens').order_by('-criado_em')

    return render(request, 'perfil/meus-pedidos.html', {'pedidos': pedidos})

@login_required
def cancelar_pedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, id=pedido_id, usuario=request.user)

    if pedido.status in ['P', 'C']:
        pedido.delete()
        messages.success(request, "Pedido Cancelado com sucesso.")
    else:
        messages.error(request, "Este pedido não pode ser Cancelado.")

    return redirect('perfil:meus_pedidos')

perfil/templates/perfil/create-user.html
{% extends "global/base.html" %}

{% block conteudo %}

<div class="form-wrapper">
    <div class="form-container">
        <h2>Faça aqui o seu Cadastro!</h2>
        
        <form 
            action="{% url 'perfil:register' %}"
            method="POST"
        >
            {% csrf_token %}

            <div class="form-content">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}

                <div class="termos-container">
                    <input type="checkbox" id="termos" name="termos" value="termos" required>
                    <label class="termos-label" for="termos">
                      Eu concordo com os <a href="#">Termos de serviço.</a>
                    </label>
                  </div>
            </div>

            <div class="form-content">
                <div class="form-group">
                    <button class="btn" type="submit">Enviar</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock conteudo %}

perfil/templates/perfil/meus-pedidos.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}
<section class="page-container">
    <div class="block-widget">
        <h1>Meus Pedidos</h1>

        {% if pedidos %}
            <table class="pedidos-table">
                <thead>
                    <tr>
                        <th>Número</th>
                        <th>Status</th>
                        <th>Total</th>
                        <th>Data</th>
                        <th>Itens</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pedido in pedidos %}
                        <tr>
                            <td>{{ pedido.numero }}</td>
                            <td>{{ pedido.get_status_display }}</td>
                            <td>R$ {{ pedido.total }}</td>
                            <td>{{ pedido.criado_em|date:"d/m/Y H:i" }}</td>
                            <td>
                                <button class="dropdown-btn" onclick="toggleDropdown('pedido-{{ pedido.id }}')">
                                    ▼
                                </button>
                            </td>
                            <td>
                                <a href="{% url 'perfil:cancelar_pedido' pedido.id %}" class="delete-btn" onclick="return confirm('Tem certeza que deseja Cancelar este pedido?')">
                                    <p class="delete-bt1">Cancelar</p>
                                </a>
                            </td>
                        </tr>
                        <tr id="pedido-{{ pedido.id }}" class="dropdown-content hidden">
                            <td colspan="6">
                                <ul style="margin:0">
                                    {% for item in pedido.itens.all %}
                                        <li class="item-c"> 
                                            <img src="{{item.imagem}}" alt="produto-img">
                                            <p class="item-p">
                                                {{ item.produto.nome }} - {{ item.quantidade }}x - R$ {{ item.preco }}
                                            </p>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>Você ainda não fez nenhum pedido.</p>
        {% endif %}
    
    </div>
</section>
{% endblock  %}