pedido/urls.py
from django.urls import path
from .views import criar_pedido, detalhe_pedido

app_name = 'pedido'

urlpatterns = [
    path('criar/', criar_pedido, name='criar'),
    path('detalhe/<int:pk>/', detalhe_pedido, name='detalhe'),
]

produto/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import index, ListaProdutos, static_view



app_name = 'produto'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('lista/<int:jogo_id>/', ListaProdutos.as_view(), name='lista'),
    path('lista/<int:jogo_id>/<slug:tipo>/', ListaProdutos.as_view(), name='lista-filtrada'),
    path('addtocart/', views.AddtoCart.as_view(), name='addtocart'),
    path('removefromcart/', views.RemoveFromCart.as_view(), name='removefromcart'),
    path('updatecart/', views.UpdateCart.as_view(), name='updatecart'),
    path('cart/', views.Cart.as_view(), name='cart'),

    path('<str:pagina>/', static_view, name="static_view"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from perfil.views import MyLoginView, createUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),

    path('accounts/login/', MyLoginView.as_view(), name='account_login'),
    path('accounts/signup/', createUser, name='account_signup'),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/models.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to='produto_imagens', blank=True, null=True)

    def __str__(self):
        return self.nome

class Produto(models.Model):
    TIPO_CHOICES = (
        ('tipo1', 'Moedas'),
        ('tipo2', 'Serviços'),
        ('tipo3', 'Gold'),
        ('tipo4', 'Outros'),
    )

    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    tipo = models.CharField(
        max_length=50,
        choices=TIPO_CHOICES,
        blank=False,
        null=False,
        default='tipo1', 
        verbose_name='Tipo'
    )
    nome = models.CharField(max_length=255, verbose_name='Nome')
    imagem = models.ImageField(upload_to='produto_imagens')
    preco_marketing = models.FloatField(default=0, verbose_name='Preço')
    preco_marketing_promo = models.FloatField(default=0, verbose_name='Preço Promo')



    def __str__(self):
        return self.nome

produto/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.views.generic.list import ListView
from django.views import View
from django.http import JsonResponse, Http404
from .models import Produto, Categoria


def index(request):
    jogos = Categoria.objects.all()
    form = AuthenticationForm()

    context = {
        'jogos': jogos,
        'loginForm': form
        }

    return render(
            request,
            'produto/index.html',
            context
        )


class ListaProdutos(ListView):
    model = Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'

    def get_queryset(self):
        categoria_id = self.kwargs.get('jogo_id')
        tipo = self.kwargs.get('tipo')
        queryset = Produto.objects.filter(categoria_id=categoria_id)

        if tipo == 'moedas':
            queryset = queryset.filter(tipo='tipo1')
        elif tipo == 'servicos':
            queryset = queryset.filter(tipo='tipo2')
        elif tipo == 'gold':
            queryset = queryset.filter(tipo='tipo3')
        elif tipo == 'outros':
            queryset = queryset.filter(tipo='tipo4')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['loginForm'] = AuthenticationForm()
        context['categoria'] = get_object_or_404(Categoria, id=self.kwargs.get('jogo_id'))
        context['jogos'] = Categoria.objects.all()
        
        tipo_escolhido = self.kwargs.get('tipo')

        if tipo_escolhido:
            context['tipo_selecionado'] = tipo_escolhido
        else:
            context['tipo_selecionado'] = 'Tudo'

        return context

class AddtoCart(View):
    def post(self, request):
        produto_id = request.POST.get('produto_id')
        produto = get_object_or_404(Produto, id=produto_id)
        carrinho = request.session.get('carrinho', {})

        if carrinho:
            primeira_categoria_id = list(carrinho.values())[0].get('categoria_id')

            if produto.categoria.id != primeira_categoria_id:
                messages.error(request, "Você só pode adicionar produtos da mesma categoria ao carrinho.")
                return redirect('produto:cart')

        if produto_id in carrinho:
            carrinho[produto_id]['quantidade'] += 1
        else:
            carrinho[produto_id] = {
                'nome': produto.nome,
                'preco': produto.preco_marketing_promo if produto.preco_marketing_promo else produto.preco_marketing,
                'quantidade': 1,
                'imagem': produto.imagem.url if produto.imagem else '',
                'categoria_id': produto.categoria.id
            }

        request.session['carrinho'] = carrinho
        return redirect('produto:cart')
    
class RemoveFromCart(View):
    def post(self, request):
        produto_id = request.POST.get('produto_id')

        carrinho = request.session.get('carrinho', {})
        if produto_id in carrinho:
            del carrinho[produto_id]

        request.session['carrinho'] = carrinho
        return redirect('produto:cart')
    

class UpdateCart(View):
    def post(self, request):
        produto_id = request.POST.get('produto_id')
        acao = request.POST.get('acao')

        carrinho = request.session.get('carrinho', {})

        if produto_id in carrinho:
            if acao == 'incrementar':
                carrinho[produto_id]['quantidade'] += 1
            elif acao == 'decrementar' and carrinho[produto_id]['quantidade'] > 1:
                carrinho[produto_id]['quantidade'] -= 1

            request.session['carrinho'] = carrinho

            subtotal = carrinho[produto_id]['quantidade'] * carrinho[produto_id]['preco']
            total = sum(item['preco'] * item['quantidade'] for item in carrinho.values())

            return JsonResponse({
                'quantidade': carrinho[produto_id]['quantidade'],
                'subtotal': subtotal,
                'total': total
            })
        else:
            return JsonResponse({'error': 'Produto não encontrado'}, status=400)

class Cart(View):
    def get(self, request):
        carrinho = request.session.get('carrinho', {})
        total = sum(item['preco'] * item['quantidade'] for item in carrinho.values())

        for produto_id, item in carrinho.items():
            item['subtotal'] = item['preco'] * item['quantidade']

        ultima_categoria_id = None
        if carrinho:
            ultima_categoria_id = list(carrinho.values())[-1].get('categoria_id', None)

        form = AuthenticationForm()
        jogos = Categoria.objects.all()
        return render(
            request, 
                'produto/cart.html', {
                'carrinho': carrinho, 
                'total': total, 
                'loginForm': form, 
                'ultima_categoria_id': ultima_categoria_id,
                'jogos': jogos
                }
        )


def static_view(request, pagina):
    templates_disponiveis = {
        "sobre": "produto/sobre.html",
        "venda-para-nos": "produto/venda.html",
        "politica-de-privacidade": "produto/politica.html",
        "faq": "produto/faq.html",
        "contato": "produto/contato.html",
    }

    template = templates_disponiveis.get(pagina)
    if not template:
        raise Http404("Página não encontrada")

    return render(request, template)

produto/templates/produto/cart.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}
<div class="cart-c">
    <div class="cart-container">
        <h2>Seu Carrinho</h2>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Produto</th>
                    <th>Preço</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Sub Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="cart-items">
                {% for produto_id, item in carrinho.items %}
                <tr data-produto-id="{{ produto_id }}">
                    <td>
                        <img class="cart-item-img" src="{{ item.imagem }}" alt="{{ item.nome }}" width="50">
                    </td>
                    <td>
                        {{ item.nome }}
                    </td>
                    <td>R$ {{ item.preco|floatformat:2 }}</td>
                    <td>
                        <button class="btn-update-cart" data-produto-id="{{ produto_id }}" data-acao="decrementar">-</button>
                    </td>
                    <td>
                        <span class="quantidade">{{ item.quantidade }}</span>
                    </td>
                    <td>
                        <button class="btn-update-cart" data-produto-id="{{ produto_id }}" data-acao="incrementar">+</button>
                    </td>
                    <td>R$ <span class="subtotal">{{ item.subtotal|floatformat:2 }}</span></td>
                    <td>
                        <form method="POST" action="{% url 'produto:removefromcart' %}">
                            {% csrf_token %}
                            <input type="hidden" name="produto_id" value="{{ produto_id }}">
                            <button class='tddd'type="submit">
                                <img class="btn-lixeira" src="{% static 'global/img/lixeira.svg' %}" alt="lixeira">
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p>Total: R$ <span id="cart-total">{{ total|floatformat:2 }}</span></p>
        <div class="cart-btn">
            {% if ultima_categoria_id %}
                <a class='continuar' href="{% url 'produto:lista' ultima_categoria_id %}">Continuar Comprando</a>
            {% else %}
                <a class='continuar' href="{% url 'produto:index' %}">Continuar Comprando</a>
            {% endif %}
            <a class='finalizar' href="{% url 'pedido:criar' %}">Finalizar Compra</a>
        </div>
    </div>
</div>
{% endblock  %}

produto/templates/produto/contato.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}


<section class="page-container">
    <div class="block-widget">
        <h2>Nossos Contatos</h2>
        <p>
            Com uma equipe dedicada, estamos sempre disponíveis para solucionar e resolver qualquer problema. Basta entrar em contato por alguns dos nossos meios e nos dizer como podemos te ajudar.
        </p>
        <p>
            <a href="">
                <img class="social-img" src="{% static 'global/img/wpp-color.svg' %}" alt="whastapp">
                WhatsApp
            </a>
        </p>
        <p>
            <a href="">
                <img class="social-img" src="{% static 'global/img/discord-color.svg' %}" alt="discord">
                Discord
            </a>
        </p>
    </div>
</section>

{% endblock  %}

produto/templates/produto/faq.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}
<section class="page-container">
    <div class="block-widget">
        <h1>FAQ - Perguntas Frequentes</h1>
        <p>Aqui você encontra respostas para as dúvidas mais comuns sobre nossos serviços.</p>

        <div class="faq-item">
            <h2>1. Como funciona a compra de game coins?</h2>
            <p>Após selecionar o jogo e a quantidade de moedas desejadas, você poderá finalizar a compra através do nosso sistema seguro de pagamento. Assim que o pagamento for confirmado, nossa equipe iniciará o processo de entrega dentro do prazo estipulado.</p>
        </div>

        <div class="faq-item">
            <h2>2. Quanto tempo leva para receber minhas moedas?</h2>
            <p>O tempo de entrega pode variar dependendo do jogo e da quantidade adquirida. Normalmente, a entrega ocorre entre alguns minutos e algumas horas após a confirmação do pagamento.</p>
        </div>

        <div class="faq-item">
            <h2>3. Como funcionam os serviços de boosting?</h2>
            <p>Nossos serviços de boosting são realizados por jogadores profissionais que acessam sua conta ou jogam em grupo com você para desbloquear recompensas ou concluir desafios específicos.</p>
        </div>

        <div class="faq-item">
            <h2>4. Minha conta corre risco ao utilizar o serviço de boosting ou compra de gamecoins?</h2>
            <p>A Venda de items e serviços por dinheiro real não é permitido pela maioria das desenvolvedoras e publicadoras de jogos online, apesar de tudo, essa pratica sempre existiu e sempre existirá por conta da demanda. Trabalhamos de forma a mitigar qualquer possibilidade de comprometer tanto nossas contas quanto as contas de nossos clientes, no entando o risco existe, apesar de baixo.</p>
        </div>

        <div class="faq-item">
            <h2>5. Quais métodos de pagamento são aceitos?</h2>
            <p>Aceitamos diversas formas de pagamento, incluindo cartões de crédito, PIX, transferências bancárias e carteiras digitais. Todas as transações são processadas por plataformas seguras.</p>
        </div>

        <div class="faq-item">
            <h2>6. O que fazer caso não receba minhas game coins?</h2>
            <p>Caso sua entrega demore mais do que o esperado, entre em contato com nossa equipe de suporte. Estamos sempre prontos para resolver qualquer problema.</p>
        </div>

        <div class="faq-item">
            <h2>7. Posso solicitar reembolso?</h2>
            <p>Trabalhamos com uma política de reembolso em casos específicos. Caso tenha algum problema com sua compra, entre em contato com nosso suporte para analisarmos sua solicitação.</p>
        </div>

        <div class="faq-item">
            <h2>8. Como entro em contato com o suporte?</h2>
            <p>Nosso suporte está disponível através do nossoo <a href="#">Discord</a> ou pelo <a href="#">WhatsApp</a></p>
        </div>
    </div>
</section>
{% endblock  %}

produto/templates/produto/index.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}
<div class="container">
    <div class="c-header">
        <div>
            <h1>
                Sua Loja de Gamecoins!
            </h1>
            <h2>
                Desde 2021 trazendo Gamecoins para você! Na nossa loja, 
                você encontra gamecoins e serviços para diversos jogos com segurança, 
                rapidez e os melhores preços. 
                Garanta suas gamecoins agora e eleve sua experiência no jogo!
            </h2>
        </div>
        <img class="bau" src="{% static 'global/img/bau.webp' %}" alt="bau">
    </div>
</div>
<div class="im-div">
    <h2> Jogos que atendemos!</h2>
</div>
<div class="carousel-container">
    <div class="carousel-wrapper">
        <button class="arrow left" onclick="scrollCarousel(-1)">&#10094;</button>
        <div class="carousel">
            {% for jogo in jogos %}
                <div class="carousel-item" onclick="redirectToProduct('{{ jogo.id }}')">
                    <img class="jogo-img" src="{{ jogo.imagem.url }}" alt="jogo-img">
                    <p>{{ jogo.nome }}</p>
                </div>
            {% endfor %}
        </div>
        <button class="arrow right" onclick="scrollCarousel(1)">&#10095;</button>
    </div>
</div>
<section class="porque-nos-escolher">
    <h2 class="titulo">Por que escolher nossa loja?</h2>
    <div class="card-container">
        <div class="card">
            <div>
                <img src="{% static "global/img/shield.svg" %}" alt="Segurança">
            </div>
            <div>
                <h3>Segurança Garantida</h3>
                <p>Transações protegidas e 100% confiáveis.</p>
            </div>
        </div>
        <div class="card">
            <div>
                <img src="{% static "global/img/truck.svg" %}" alt="Entrega">
            </div>
            <div>
                <h3>Entrega Rápida</h3>
                <p>Receba suas gamecoins em poucos minutos.</p>
            </div>
        </div>
        <div class="card">
            <div>
                <img src="{% static "global/img/support.svg" %}" alt="Suporte">
            </div>
            <div>
                <h3>Suporte</h3>
                <p>Atendimento ágil e sempre disponível.</p>
            </div>
        </div>
        <div class="card">
            <div>
                <img src="{% static "global/img/preco.svg" %}" alt="Preço">
            </div>
            <div>
                <h3>Melhor Preço</h3>
                <p>Valores justos e promoções frequentes.</p>
            </div>
        </div>
    </div>
</section>

{% endblock  %}

produto/templates/produto/lista.html
{% extends "global/base.html" %}
{% load omfilters %}
{% load static %}
{% block conteudo %}

<div class="area-container">
    <ul class="area">
        <li>
            <a href="{% url "produto:index" %}">
                Home
            </a>
        </li>
        <li>
            <a href="#">
                {{categoria}}
            </a>
        </li>
        <li>
            <a href="">
                {{ tipo_selecionado|capfirst }}
            </a>
        </li>
    </ul>
    <div class="type-filter">
        <ul>
            <li class="{% if tipo_selecionado == 'Tudo' %}active{% endif %}">
                <a href="{% url 'produto:lista' jogo_id=categoria.id %}">Tudo</a>
            </li>
            <li class="{% if tipo_selecionado == 'moedas' %}active{% endif %}">
                <a href="{% url 'produto:lista-filtrada' jogo_id=categoria.id tipo='moedas' %}">Moedas</a>
            </li>
    
            <li class="{% if tipo_selecionado == 'servicos' %}active{% endif %}">
                <a href="{% url 'produto:lista-filtrada' jogo_id=categoria.id tipo='servicos' %}">Serviços</a>
            </li>
    
            <li class="{% if tipo_selecionado == 'gold' %}active{% endif %}">
                <a href="{% url 'produto:lista-filtrada' jogo_id=categoria.id tipo='gold' %}">Gold</a>
            </li>
    
            <li class="{% if tipo_selecionado == 'outros' %}active{% endif %}">
                <a href="{% url 'produto:lista-filtrada' jogo_id=categoria.id tipo='outros' %}">Outros</a>
            </li>
        </ul>
    </div>
</div>
<div class='master-grid'>
    <div  class='grid-container'>
        {% for produto in produtos %}
        <div class="grid-item"> 
            <div class="item-icon"> 
                <img class="item-img" src="{{ produto.imagem.url }}" alt="imagem">
            </div>
            <div class="item-content">
                <div class="item-description">{{produto.nome}}</div>
                <div class="item-prices">
                    <span class="price-value">{{produto.preco_marketing_promo | formata_preco}}</span>
                    <span class="price-promo-value">{{produto.preco_marketing | formata_preco}}</span>
                </div>
            </div>
            <div class="item-buy">
            <form method="POST" action="{% url 'produto:addtocart' %}">
                {% csrf_token %}
                <input type="hidden" name="produto_id" value="{{ produto.id }}">
                <button type="submit">
                    <img class="btn-carrinho" src="{% static 'global/img/cart.svg' %}" alt="carrinho">
                    COMPRAR!
                </button>
            </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock  %}

produto/templates/produto/politica.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}
<section class="page-container">
    <div class="block-widget">
        <h1>Política de Privacidade</h1>

        <p>A <strong>[XXXXXXXXXXXX]</strong> respeita sua privacidade e se compromete a proteger os dados pessoais dos seus usuários. Esta Política de Privacidade explica como coletamos, usamos, armazenamos e protegemos suas informações ao utilizar nosso site e serviços.</p>

        <h2>1. Informações que Coletamos</h2>
        <h3>1.1 Informações Pessoais</h3>
        <p>Coletamos informações pessoais apenas quando necessário para processar transações e garantir a segurança do usuário. Essas informações podem incluir:</p>
        <ul>
            <li>Nome completo</li>
            <li>Endereço de e-mail</li>
            <li>Informações de pagamento (processadas por plataformas seguras de terceiros)</li>
            <li>Endereço IP e dados de acesso</li>
        </ul>

        <h3>1.2 Informações de Navegação e Cookies</h3>
        <p>Podemos coletar automaticamente algumas informações para melhorar sua experiência no site, como:</p>
        <ul>
            <li>Tipo de dispositivo e navegador utilizado</li>
            <li>Páginas acessadas dentro do site</li>
            <li>Cookies e tecnologias de rastreamento para personalização da experiência e segurança</li>
        </ul>
        <p>Você pode gerenciar suas preferências de cookies diretamente no seu navegador.</p>

        <h2>2. Como Utilizamos Suas Informações</h2>
        <p>Utilizamos as informações coletadas para:</p>
        <ul>
            <li>Processar compras de game coins e serviços de boosting</li>
            <li>Garantir a segurança das transações e a autenticidade do usuário</li>
            <li>Melhorar a experiência do cliente e personalizar ofertas</li>
            <li>Cumprir obrigações legais e prevenir fraudes</li>
        </ul>

        <h2>3. Compartilhamento de Dados</h2>
        <p>Não vendemos, compartilhamos ou divulgamos suas informações pessoais para terceiros, exceto nas seguintes situações:</p>
        <ul>
            <li>Quando necessário para processar pagamentos via parceiros confiáveis</li>
            <li>Para cumprimento de exigências legais, como ordens judiciais</li>
            <li>Para prevenção de fraudes e segurança da plataforma</li>
        </ul>

        <h2>4. Segurança das Informações</h2>
        <p>Implementamos medidas de segurança para proteger suas informações contra acessos não autorizados, perdas ou alterações. Essas medidas incluem:</p>
        <ul>
            <li>Criptografia de dados</li>
            <li>Firewalls e sistemas de proteção contra ataques</li>
            <li>Acesso restrito a informações sensíveis</li>
        </ul>
        <p>Recomendamos que os usuários também tomem precauções, como o uso de senhas seguras.</p>

        <h2>5. Uso de Cookies e Publicidade</h2>
        <p>Nosso site utiliza cookies para melhorar a experiência do usuário e exibir anúncios personalizados. Cookies publicitários podem ser utilizados por parceiros para exibir anúncios relevantes com base na sua navegação.</p>
        <p>Se desejar, você pode desativar o uso de cookies diretamente nas configurações do seu navegador.</p>

        <h2>6. Direitos do Usuário</h2>
        <p>Você tem direito a:</p>
        <ul>
            <li>Solicitar a exclusão dos seus dados pessoais de nossos sistemas</li>
            <li>Acessar e corrigir suas informações</li>
            <li>Revogar consentimentos de coleta de dados</li>
        </ul>

        <h2>7. Alterações nesta Política</h2>
        <p>Podemos atualizar esta Política de Privacidade periodicamente para refletir mudanças nos nossos serviços ou nas leis aplicáveis. Notificaremos os usuários sempre que houver alterações significativas.</p>
        <p>Recomendamos que você revise esta política regularmente para estar ciente das nossas práticas.</p>

    </div>
</section>
{% endblock  %}

produto/templates/produto/sobre.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}


<section class="page-container">
    <div class="block-widget">
        <h2>Sobre Nós</h2>
        <p>
            Fundada em 2021, nossa empresa nasceu com o propósito de oferecer uma experiência segura 
            e confiável para os gamers que buscam melhorar seu desempenho ou adquirir gamecoins para 
            seus jogos favoritos. Com uma equipe apaixonada por games e dedicada ao atendimento de 
            qualidade, garantimos uma jornada transparente e eficiente para todos os nossos clientes. 
            Nosso compromisso é proporcionar um serviço ágil, seguro e acessível, garantindo que 
            cada transação seja realizada com total profissionalismo.
        </p>
    
        <h2>Nossos Produtos</h2>
        <p>
            Trabalhamos com gamecoins para diversos jogos, permitindo que nossos clientes ampliem 
            suas possibilidades dentro do universo gamer. Além disso, oferecemos serviços de boosting 
            para quem deseja alcançar novos níveis, desbloquear conquistas e melhorar seu desempenho 
            sem complicações. Todos os nossos produtos são entregues de maneira rápida e segura, com 
            total garantia para que você possa aproveitar ao máximo sua experiência de jogo.
        </p>
    
        <h2>Nossos Serviços</h2>
        <p>
            Nosso site foi desenvolvido para oferecer uma navegação intuitiva e um processo de compra 
            simples e seguro. Além de garantir transações protegidas, contamos com um suporte 
            especializado pronto para auxiliar nossos clientes em cada etapa da jornada. Seja 
            para a aquisição de gamecoins ou para serviços de boosting, prezamos pelo profissionalismo, 
            eficiência e satisfação total de quem confia em nosso trabalho.
        </p>
    </div>

</section>



{% endblock  %}

produto/templates/produto/venda.html
{% extends "global/base.html" %}
{% load static %}
{% block conteudo %}
<section class="page-container">
    <div class="block-widget">
        <h2>Venda para Nós</h2>
        <p>
            Compramos suas gamecoins com o melhor ratio do mercado, basta entrar em contato com 
            uma breve descrição, quantidade e jogo que deseja fazer a venda. Nossa equipe estará 
            sempre de prontidão para atender e negociar de maneira rápida e segura.
        </p>
        <p>
            <a href="">
                <img class="social-img" src="{% static 'global/img/wpp-color.svg' %}" alt="whastapp">
                WhatsApp
            </a>
        </p>
        <p>
            <a href="">
                <img class="social-img" src="{% static 'global/img/discord-color.svg' %}" alt="discord">
                Discord
            </a>
        </p>
    </div>

</section>
{% endblock  %}